### ISSUE TITLE
Disable Scala.js on Dotty until 0.28.0-RC1

### ISSUE THREAD

**Issue by mpilquist** [djspiewak/sbt-spiewak#13]
See https://github.com/scalameta/munit/issues/199#issuecomment-692730141

In essence, due to some issues with Dotty 0.27.0-RC1, munit cannot build for Scala.js yet, which means just about every downstream project of sbt-spiewak will need workarounds until 0.28.0-RC1. It might be better to just restore the 0.15.2 Dotty/Scala.JS exclusions for now.

**Comment by djspiewak** [comment]
Hmm. Cats Effect is actually building on DottyJS (on both 2.x and 3.x now), though 3.x does have a workaround for that particular bug. I wonder if it's just worth tossing a `enableDottyJS` key in there or something to make it easier. This is a pretty temporary thing though, as you pointed out. For the time being, downstream projects can achieve the same effect by adding the following line:

```scala
.jsSettings(crossScalaVersions -= "0.27.0-RC1")
```

If you toss on any cross project definition, DottyJS will be effectively disabled.

**Comment by larsrh** [comment]
I think this can be closed now.
