### ISSUE TITLE
scala-2 and scala-3 source directories refer to project base directory, not module directory

### ISSUE THREAD

**Issue by mpilquist** [djspiewak/sbt-spiewak#14]
https://github.com/djspiewak/sbt-spiewak/commit/2bce0b422cc43c490c30ad1e89122ccd2c4181b1#diff-4dd98e212dbd5661e10c547bdb06116eR460

```
sbt:root> project io
[info] set current project to fs2-io (in build file:/Users/MPilqu0037e/Development/oss/fs2/)
sbt:fs2-io> show unmanagedSourceDirectories
[info] * /.../oss/fs2/io/src/main/scala-0.27
[info] * /.../oss/fs2/io/src/main/scala
[info] * /.../oss/fs2/io/src/main/java
[info] * /.../oss/fs2/src/main/scala-3
[info] * /.../oss/fs2/shared/src/main/scala-3
```

Path should be `/.../oss/fs2/io/src/main/scala-3`

**Comment by joroKr21** [comment]
And in the root project they refer to the parent directory.
This causing Intellij to import my entire folder of OSS projects 🙈 
No wonder indexing takes a while 😂

**Comment by mpilquist** [comment]
BTW, this can be removed entirely from this plugin now that it's built in to SBT

**Comment by joroKr21** [comment]
> BTW, this can be removed entirely from this plugin now that it's built in to SBT

Where can I find information about this?

**Comment by mpilquist** [comment]
https://github.com/sbt/sbt/issues/5895

**Comment by joroKr21** [comment]
Thanks, I didn't find this anywhere in release notes so I was confused

**Comment by jastice** [comment]
related IntelliJ issue: https://youtrack.jetbrains.com/issue/SCL-18504
