### ISSUE TITLE
FullScalaVersion.unapply does not handle `3.0.0-RC1-bin-SNAPSHOT`

### ISSUE THREAD

**Issue by griggt** [djspiewak/sbt-spiewak#34]
As a result the cats-effect projects in the Dotty community build broke after the recent version bump: https://github.com/lampepfl/dotty/issues/10478

**Comment by djspiewak** [comment]
Uh… why is this a version pattern that you're using? :-(

**Comment by griggt** [comment]
Thanks for the quick fix, apologies for dragging you into the firefighting.
